#!/usr/bin/env perl
# Copyright 2024 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
#
# Generate error table for Beehive from errno.h file

use strict;

my $command = "mkerrors_beehive.pl " . join(' ', @ARGV);

my %errstr = ();

print <<EOF;
// $command
// Code generated by the command above; DO NOT EDIT.

package syscall

const (
EOF

while(<>){
	if(/^#define\sERR(\w+)\s\(([0-9]+)\)\s+\/\/\s(.*)$/){
		my $name = $1;
		my $num = $2;
		my $str = $3;

		$errstr{$name} = $str;

		print "E$name = Errno($num); \n";
	}
}

print <<EOF;
)

// Error strings for invented errors
var errors = [...]string{
EOF

foreach my $k ( sort keys %errstr ) {
	print "E$k:\"@errstr{$k}\",\n";
}

print <<EOF;
}
EOF