// mkerrors_beehive.pl
// Code generated by the command above; DO NOT EDIT.

package syscall

const (
	ENOSYS     = Errno(1)
	EINTR      = Errno(2)
	EACCESS    = Errno(3)
	EFAULT     = Errno(4)
	ENOPROC    = Errno(5)
	ESIZE      = Errno(6)
	EEXISTS    = Errno(7)
	EEXHAUSTED = Errno(8)
	EINUSE     = Errno(9)
	EAGAIN     = Errno(10)
	EINVAL     = Errno(11)
	ENOMEM     = Errno(12)
	ENOENT     = Errno(13)
)

// Error strings for invented errors
var errors = [...]string{
	EACCESS:    "access forbidden",
	EAGAIN:     "attempt syscall again",
	EEXHAUSTED: "resource limits exhausted",
	EEXISTS:    "resource already exists",
	EFAULT:     "general fault",
	EINTR:      "syscall was interrupted",
	EINUSE:     "resource in use",
	EINVAL:     "invalid parameters",
	ENOENT:     "no such resource",
	ENOMEM:     "no memory available",
	ENOPROC:    "no matching process",
	ENOSYS:     "no system call exists",
	ESIZE:      "bad size",
}
