// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types_beehive.go | go run mkpost.go

package syscall

type (
	_C_short     int16
	_C_int       int32
	_C_long      int64
	_C_long_long int64
)

type Timespec struct {
	Sec  _C_long_long
	Nsec _C_long_long
}

type Timeval struct {
	Sec  _C_long_long
	Usec _C_long_long
}
